#!/bin/sh
# Source: https://github.com/kaczor6418/git-hooks-example/tree/master
SRC="^source/.*.js$"
linter_exit_code=1
staged_js_files=$(git diff --cached --diff-filter=d --name-only | grep $SRC)
./node_modules/.bin/eslint $staged_js_files
linter_exit_code=$?
if [ $linter_exit_code -ne 0 ]
then
  echo "❌ Linter errors have occurred"
  exit 1
else
  echo "✔ Eslint did not find any errors"
  exit 0
fi